# BUILD STAGE
FROM golang:1.20.0-alpine as build

LABEL maintainer="leoff00"

WORKDIR /go/producer

COPY . /go/producer/

RUN CGO_ENABLED=0 go build -o bin/producer cmd/producer/main.go

# RELEASE STAGE
FROM alpine:3.19 

WORKDIR /

RUN mkdir input
RUN mkdir conciliation

COPY --from=build /go/producer /

EXPOSE 4000

ENTRYPOINT [ "./producer" ]
